---
ca_directory: "/ridelab-data/pki"
ca_key_name: "ridelab_root.key"
ca_cert_name: "ridelab_root.crt"
ca_csr_name: "ridelab_root.csr"
s3_backup_bucket: "ridelab-backups"
backup_role_name: "Ridelab-Backup-Role"
backup_profile_name: "Ridelab-Backup-Profile"
