---
- name: Ensure apps directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'
  loop:
    - "/ridelab-data/deploy-apps"
    - "/ridelab-data/deploy-apps/ride-admin"

- name: Sync deployment script
  ansible.builtin.copy:
    src: "deploy.sh"
    dest: "/home/{{ local_user }}/deploy.sh"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'
