- name: Ensure Traefik base directory exists
  ansible.builtin.file:
    path: /ridelab-data/traefik
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0755'

- name: Sync traefik configuration from repo
  ansible.builtin.copy:
    src: "traefik.yml"
    dest: "/ridelab-data/traefik/traefik.yml"
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: '0644'
