- name: Ensure Let's Encrypt directory exists
  ansible.builtin.file:
    path: /home/{{ local_user  }}/projects/homelab/traefik/letsencrypt
    state: directory
    owner: 1000
    group: 1000
    mode: '0700'

- name: Ensure acme.json exists
  ansible.builtin.file:
    path: /home/{{ local_user  }}/projects/homelab/traefik/letsencrypt/acme.json
    state: touch
    owner: 1000
    group: 1000
    mode: '0600'
